spring.application.name=learning-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/learningplatform
spring.datasource.username=postgres
spring.datasource.password=Poseidon137
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html